name: Compile PS3 SPRX
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    # On utilise la nouvelle adresse officielle de la communauté ps3dev
    container: ghcr.io/ps3dev/ps3dev:master

    steps:
      - uses: actions/checkout@v4

      - name: Compile
        run: |
          make

      - name: Upload SPRX
        uses: actions/upload-artifact@v4
        with:
          name: MonMenuPS3
          path: ADF_Menu.sprx
